// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AdvertisingDate
    {
        public int AdvertisingDateId { get; set; }
        public int? ContractId { get; set; }
        public DateTime? AdvertisingDate1 { get; set; }

        public virtual Contract Contract { get; set; }
    }
}