// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AnalysisTypeLookup
    {
        public int TypeId { get; set; }
        public string TypeCode { get; set; }
        public string TypeDescription { get; set; }
    }
}