// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Appraisal
    {
        public int AppraisalId { get; set; }
        public int? Paid { get; set; }
        public int? IssueId { get; set; }
        public string Quality { get; set; }
        public string Punctuality { get; set; }
        public string Evaluation { get; set; }
        public string Justification { get; set; }
        public string JustificationDetail { get; set; }

        public virtual Issue Issue { get; set; }
        public virtual AssessmentMetadatum Pa { get; set; }
    }
}