// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ArtifactManagementLog
    {
        public ArtifactManagementLog()
        {
            ArtifactManagementDetailLogs = new HashSet<ArtifactManagementDetailLog>();
        }

        public int LogId { get; set; }
        public string PrimaryArtifactType { get; set; }
        public int PrimaryArtifactKey { get; set; }
        public string Description { get; set; }
        public string Action { get; set; }
        public int? MoveTargetKey { get; set; }
        public string MoveTargetName { get; set; }
        public string UserName { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<ArtifactManagementDetailLog> ArtifactManagementDetailLogs { get; set; }
    }
}