// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AssessmentMetadatum
    {
        public AssessmentMetadatum()
        {
            Appraisals = new HashSet<Appraisal>();
            DisputedIssues = new HashSet<DisputedIssue>();
        }

        public int Paid { get; set; }
        public int? ActivityNo { get; set; }
        public int? AppraisableId { get; set; }
        public int? ContractForStaff { get; set; }
        public string Appraisee { get; set; }
        public string ActivityType { get; set; }
        public string AppraisableType { get; set; }
        public DateTime? DateOfAssessment { get; set; }
        public string Location { get; set; }
        public int? KeyStaffId { get; set; }
        public string Position { get; set; }
        public string AppraisalStatus { get; set; }
        public DateTime? AssessmentPeriodFrom { get; set; }
        public DateTime? AssessmentPeriodTo { get; set; }
        public int? LastIssueId { get; set; }
        public bool? IsComplete { get; set; }
        public DateTime? DateSaved { get; set; }
        public decimal? PerformanceAgainstPlan { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastEditedBy { get; set; }
        public string Assessor { get; set; }

        public virtual Contract ContractForStaffNavigation { get; set; }
        public virtual KeyStaffRegister KeyStaff { get; set; }
        public virtual AssessmentScoreLog AssessmentScoreLog { get; set; }
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        public virtual ICollection<DisputedIssue> DisputedIssues { get; set; }
    }
}