// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AssessmentScoreLog
    {
        public int Paid { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal? QpAssessment { get; set; }
        public decimal? QualityScore { get; set; }
        public decimal? PunctualityScore { get; set; }
        public decimal? PapScore { get; set; }
        public bool? PapGreenFlag { get; set; }
        public bool? PapRedFlag { get; set; }
        public string PapMessage { get; set; }
        public DateTime? PapDate { get; set; }
        public decimal? Mpr { get; set; }
        public decimal? Epr { get; set; }
        public decimal? AggregateMpr { get; set; }
        public decimal? AggregateEpr { get; set; }
        public decimal? Opr { get; set; }
        public decimal? Mypr { get; set; }
        public DateTime? MyprStartDate { get; set; }
        public DateTime? MyprEndDate { get; set; }
        public int? GreenFlag { get; set; }
        public int? RedFlag { get; set; }
        public int? MonitoringStartNumber { get; set; }
        public int? MonitoringEndNumber { get; set; }
        public int? EvaluationStartNumber { get; set; }
        public int? EvaluationEndNumber { get; set; }

        public virtual AssessmentMetadatum Pa { get; set; }
    }
}