// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AssessmentRegisterView
    {
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public string Category { get; set; }
        public string ContractType { get; set; }
        public int ContractId { get; set; }
        public string ControllingRegion { get; set; }
        public string FirmName { get; set; }
        public int Paid { get; set; }
        public int? ActivityNo { get; set; }
        public string Appraisee { get; set; }
        public string ActivityType { get; set; }
        public DateTime? DateOfAssessment { get; set; }
        public string AppraisalStatus { get; set; }
        public DateTime? DateSaved { get; set; }
        public string LastEditedBy { get; set; }
        public string AppraisableType { get; set; }
        public decimal? Mpr { get; set; }
        public decimal? Epr { get; set; }
        public decimal? PapScore { get; set; }
        public int? GreenFlag { get; set; }
        public int? RedFlag { get; set; }
    }
}