// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AssessedContract
    {
        public int? AppraisableId { get; set; }
        public int Paid { get; set; }
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public string ContractType { get; set; }
        public string ControllingRegion { get; set; }
        public string AppraisableType { get; set; }
    }
}