// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class BidItem
    {
        public int BidItemId { get; set; }
        public int? BidDivisionId { get; set; }
        public int? ItemId { get; set; }
        public string CustomItemCode { get; set; }
        public decimal? OriginalQuantity { get; set; }
        public decimal? NewQuantity { get; set; }
        public decimal? ContractorRate { get; set; }
        public bool? IsSps { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public decimal? DiscountedRate { get; set; }

        public virtual BidDivision BidDivision { get; set; }
        public virtual Item Item { get; set; }
    }
}