// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class BoQitemEntry
    {
        public int BoQitemEntryId { get; set; }
        public int? BoQdivisionEntryId { get; set; }
        public int? ItemId { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Rate { get; set; }
        public byte[] RateEncrypted { get; set; }
        public decimal? RateDecrypted { get; set; }
        public bool? IsSps { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public decimal? Total { get; set; }

        public virtual BoQdivisionEntry BoQdivisionEntry { get; set; }
        public virtual Item Item { get; set; }
    }
}