// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class BoQseriesEntry
    {
        public BoQseriesEntry()
        {
            BoQdivisionEntries = new HashSet<BoQdivisionEntry>();
        }

        public int BoQseriesEntryId { get; set; }
        public int? BoQid { get; set; }
        public string SeriesCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string SpecificationName { get; set; }

        public virtual BoQ BoQ { get; set; }
        public virtual Series S { get; set; }
        public virtual ICollection<BoQdivisionEntry> BoQdivisionEntries { get; set; }
    }
}