// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ClaimCategory
    {
        public ClaimCategory()
        {
            Claims = new HashSet<Claim>();
        }

        public string ClaimCategory1 { get; set; }
        public string TypeofClaim { get; set; }

        public virtual ICollection<Claim> Claims { get; set; }
    }
}