// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ConsultantsPerformance
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? SubmissionDate { get; set; }
        public int DeliverableId { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public decimal MonetaryValue { get; set; }
        public decimal PercentComplete { get; set; }
        public DateTime AssessmentDate { get; set; }
        public string DetailedReason { get; set; }
        public string Reason { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Deliverable Deliverable { get; set; }
    }
}