// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ContractType
    {
        public ContractType()
        {
            Contracts = new HashSet<Contract>();
        }

        public string ContractType1 { get; set; }
        public string Category { get; set; }

        public virtual ICollection<Contract> Contracts { get; set; }
    }
}