// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ContractPhase
    {
        public ContractPhase()
        {
            Deliverables = new HashSet<Deliverable>();
            InverseContractPhaseNavigation = new HashSet<ContractPhase>();
            PhaseCurrencyBreakdowns = new HashSet<PhaseCurrencyBreakdown>();
        }

        public int Id { get; set; }
        public int ContractId { get; set; }
        public string Description { get; set; }
        public DateTime EndDate { get; set; }
        public decimal LumpSum { get; set; }
        public string Name { get; set; }
        public decimal Reimbursable { get; set; }
        public DateTime StartDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public int? SupplementId { get; set; }
        public int? ContractPhaseId { get; set; }
        public int? ReplacedSupplementId { get; set; }
        public decimal ProvisionalSum { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal AdvancePercent { get; set; }
        public bool IsAdvanceNotTaken { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ContractPhase ContractPhaseNavigation { get; set; }
        public virtual Supplement ReplacedSupplement { get; set; }
        public virtual Supplement Supplement { get; set; }
        public virtual ICollection<Deliverable> Deliverables { get; set; }
        public virtual ICollection<ContractPhase> InverseContractPhaseNavigation { get; set; }
        public virtual ICollection<PhaseCurrencyBreakdown> PhaseCurrencyBreakdowns { get; set; }
    }
}