// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ContractPerformanceScore
    {
        public int ContractId { get; set; }
        public int PreEvaluationId { get; set; }
        public int? PasScore { get; set; }
        public decimal? QualityScore { get; set; }
        public decimal? PunctualityScore { get; set; }
        public int? QualityGreenFlags { get; set; }
        public int? PunctualityGreenFlags { get; set; }
        public int? WeightedPasGreenFlags { get; set; }
        public int? QualityRedFlags { get; set; }
        public int? PunctualityRedFlags { get; set; }
        public int? WeightedPasRedFlags { get; set; }
        public decimal? PapScore { get; set; }
        public DateTime? PapMeasurementDate { get; set; }
        public string PapMessage { get; set; }
        public int? PapGreenFlag { get; set; }
        public int? PapRedFlag { get; set; }
        public decimal? PerformanceRating { get; set; }
        public int? WeightedGreenFlags { get; set; }
        public int? WeightedRedFlags { get; set; }
    }
}