// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ContractProgressAsNew
    {
        public int ContractProgressId { get; set; }
        public int? ContractId { get; set; }
        public decimal? ContractProgres { get; set; }
        public decimal? WorksProgress { get; set; }
        public string Status { get; set; }
        public bool? IsApproval { get; set; }
        public bool? IsApprovalByDirector { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string LastEditedBy { get; set; }
    }
}