// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ContractProgressPerformanceScore
    {
        public int Ppid { get; set; }
        public int? ContractId { get; set; }
        public int? MeasurementId { get; set; }
        public decimal? ProgressPerformance { get; set; }
        public string ProgressPerformanceMessage { get; set; }
        public bool? RedFlag { get; set; }
        public bool? GreenFlag { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Measurement Measurement { get; set; }
    }
}