// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Correspondence
    {
        public int CorrespondenceId { get; set; }
        public DateTime? Date { get; set; }
        public string Reference { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Description { get; set; }
        public int? VariationOrderId { get; set; }
        public int? ClaimId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string LastEditedBy { get; set; }
        public string CreatedBy { get; set; }

        public virtual Claim Claim { get; set; }
        public virtual VariationOrder VariationOrder { get; set; }
    }
}