// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class CurrencyLookup
    {
        public int CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencySign { get; set; }
    }
}