// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class DeliverableLookup
    {
        public DeliverableLookup()
        {
            Deliverables = new HashSet<Deliverable>();
        }

        public int Id { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Deliverable> Deliverables { get; set; }
    }
}