// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Deliverable
    {
        public Deliverable()
        {
            ConsultantsPerformances = new HashSet<ConsultantsPerformance>();
            ConsultantsPrograms = new HashSet<ConsultantsProgram>();
        }

        public int Id { get; set; }
        public decimal PhasePercentage { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public int ContractId { get; set; }
        public decimal MonetaryValue { get; set; }
        public int ContractPhaseId { get; set; }
        public int DeliverableLookupId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ContractPhase ContractPhase { get; set; }
        public virtual DeliverableLookup DeliverableLookup { get; set; }
        public virtual ICollection<ConsultantsPerformance> ConsultantsPerformances { get; set; }
        public virtual ICollection<ConsultantsProgram> ConsultantsPrograms { get; set; }
    }
}