// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Discussion
    {
        public int DiscussionId { get; set; }
        public int ContractId { get; set; }
        public string UserName { get; set; }
        public string UserPosition { get; set; }
        public string UserDirectorate { get; set; }
        public string Point { get; set; }
        public DateTime Time { get; set; }

        public virtual Contract Contract { get; set; }
    }
}