// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class DisputedIssue
    {
        public int DisputedIssueId { get; set; }
        public int? Paid { get; set; }
        public string Reference { get; set; }
        public string NatureOfDispute { get; set; }
        public int? IssueId { get; set; }

        public virtual Issue Issue { get; set; }
        public virtual AssessmentMetadatum Pa { get; set; }
    }
}