// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Division
    {
        public Division()
        {
            BidDivisions = new HashSet<BidDivision>();
            BoQdivisionEntries = new HashSet<BoQdivisionEntry>();
            Items = new HashSet<Item>();
        }

        public string SeriesCode { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionDescription { get; set; }
        public string SpecificationName { get; set; }

        public virtual Series S { get; set; }
        public virtual ICollection<BidDivision> BidDivisions { get; set; }
        public virtual ICollection<BoQdivisionEntry> BoQdivisionEntries { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}