// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EngineeringEstimate
    {
        public EngineeringEstimate()
        {
            Altitudes = new HashSet<Altitude>();
            Bids = new HashSet<Bid>();
            BoQs = new HashSet<BoQ>();
            Contracts = new HashSet<Contract>();
            FundSources = new HashSet<FundSource>();
            RoadProperties = new HashSet<RoadProperty>();
            Tenders = new HashSet<Tender>();
            Terrains = new HashSet<Terrain>();
            TownsPasseds = new HashSet<TownsPassed>();
        }

        public int EngineeringEstimateId { get; set; }
        public string Description { get; set; }
        public string DerivedEstimateName { get; set; }
        public int DesignContractId { get; set; }
        public DateTime? DateOfEstimate { get; set; }
        public string BidType { get; set; }
        public string FunctionalClassification { get; set; }
        public string RoadNumber { get; set; }
        public string FormOfContract { get; set; }
        public string SpecificationForm { get; set; }
        public string DesignStandard { get; set; }
        public string Climate { get; set; }
        public string DesignTrafficVolume { get; set; }
        public decimal? TrafficVolume { get; set; }
        public int? TotalBridges { get; set; }
        public decimal? BridgeLength { get; set; }
        public decimal? MaximumSpanLenght { get; set; }
        public int? TotalCulverts { get; set; }
        public decimal? CulvertLength { get; set; }
        public string StartRegion { get; set; }
        public string EndRegion { get; set; }
        public string StartPlace { get; set; }
        public string EndPlace { get; set; }
        public decimal? OneTimeVariationOrderLimit { get; set; }
        public decimal? MultipleVariationOrderLimitInPercentage { get; set; }
        public decimal? SiteOverhead { get; set; }
        public decimal? Hqoverhead { get; set; }
        public decimal? Profit { get; set; }
        public decimal? Risk { get; set; }
        public decimal? HaulEarthWorkToPlacing { get; set; }
        public decimal? HaulAggregateToPlacing { get; set; }
        public decimal? HaulBitumenToPlacing { get; set; }
        public decimal? HaulAggregateToBitumenPlant { get; set; }
        public decimal? HaulAggregateToConcretePrecastSite { get; set; }
        public decimal? HaulPrecastConcreteMaterialToPlacing { get; set; }
        public decimal? HaulConcreteToBridges { get; set; }
        public decimal? HaulCementToSite { get; set; }
        public decimal? HaulSandToSite { get; set; }
        public decimal? HaulSiteWonSandToPlacing { get; set; }
        public decimal? HaulSelectedEarthworksToPlacing { get; set; }
        public decimal? HaulGravelToPlacing { get; set; }
        public decimal? DistanceFromAddisAbaba { get; set; }
        public bool? ItemRateIncludesVat { get; set; }
        public decimal? Vat { get; set; }
        public decimal? Contingency { get; set; }
        public bool? DeductDayworksForContingency { get; set; }
        public bool? IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string ApprovedReversedBy { get; set; }
        public DateTime? ApprovalReversedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool? HasBoq { get; set; }

        public virtual Contract DesignContract { get; set; }
        public virtual ICollection<Altitude> Altitudes { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<BoQ> BoQs { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<FundSource> FundSources { get; set; }
        public virtual ICollection<RoadProperty> RoadProperties { get; set; }
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual ICollection<Terrain> Terrains { get; set; }
        public virtual ICollection<TownsPassed> TownsPasseds { get; set; }
    }
}