// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EquipmentCostLocal
    {
        public EquipmentCostLocal()
        {
            LabourCostLocals = new HashSet<LabourCostLocal>();
        }

        public int PlantCostId { get; set; }
        public int? MaterialId { get; set; }
        public int? HauledMaterialId { get; set; }
        public string HaulType { get; set; }
        public int? EquipmentType { get; set; }
        public int? MaterialCostId { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Cost { get; set; }
        public string Activity { get; set; }
        public bool? RentalRate { get; set; }
        public bool? CalculatedRate { get; set; }
        public string Note { get; set; }

        public virtual Equipment EquipmentTypeNavigation { get; set; }
        public virtual Material Material { get; set; }
        public virtual MaterialCostLocal MaterialCost { get; set; }
        public virtual ICollection<LabourCostLocal> LabourCostLocals { get; set; }
    }
}