// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Equipment
    {
        public Equipment()
        {
            EquipmentCostLocals = new HashSet<EquipmentCostLocal>();
            EquipmentCosts = new HashSet<EquipmentCost>();
        }

        public int EquipmentId { get; set; }
        public string Classification { get; set; }
        public string Subclassification { get; set; }
        public string EquipmentType { get; set; }
        public bool IsTurboCharged { get; set; }
        public string RatedCapacity { get; set; }
        public int? Hp { get; set; }
        public int? LabourId { get; set; }
        public decimal? EquipmentInitialCost { get; set; }
        public decimal? SalvageRate { get; set; }
        public decimal? TyreSetPrice { get; set; }
        public int? EquipmentLifeTime { get; set; }
        public decimal? InsuranceRate { get; set; }
        public decimal? RepairCostFactor { get; set; }
        public decimal? FuelConsumptionFactor { get; set; }
        public decimal? EfficiencyFactor { get; set; }
        public decimal? ServiceCostFactor { get; set; }
        public int? TyreLife { get; set; }
        public decimal? TruckCapacity { get; set; }
        public decimal? HourlyRate { get; set; }
        public decimal? HourlyRentalRate { get; set; }
        public decimal? HourlyRatePlusOperationalCost { get; set; }
        public string Note { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public bool IsMaintenanceEquipment { get; set; }

        public virtual EquipmentClassification ClassificationNavigation { get; set; }
        public virtual Labour Labour { get; set; }
        public virtual ICollection<EquipmentCostLocal> EquipmentCostLocals { get; set; }
        public virtual ICollection<EquipmentCost> EquipmentCosts { get; set; }
    }
}