// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EquipmentClassification
    {
        public EquipmentClassification()
        {
            Equipment = new HashSet<Equipment>();
        }

        public string Classification { get; set; }

        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}