// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EramsFlag
    {
        public int FlagId { get; set; }
        public bool IsRateBuildupDirty { get; set; }
    }
}