// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EramsBackupMetadatum
    {
        public int EramsBackupId { get; set; }
        public DateTime Date { get; set; }
        public int BackupCount { get; set; }
        public string PhysicalLocation { get; set; }
        public string BackupName { get; set; }
        public string CreatedBy { get; set; }
    }
}