// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ErrorReport
    {
        public int ErrorId { get; set; }
        public int? ContractId { get; set; }
        public string ControllingRegion { get; set; }
        public string ContractType { get; set; }
        public string UserId { get; set; }
        public string Position { get; set; }
        public string ProblemMoudle { get; set; }
        public string ProblemDetail { get; set; }
        public string ReportedBy { get; set; }
        public string PhoneNo { get; set; }
        public DateTime? ReportedDate { get; set; }

        public virtual Contract Contract { get; set; }
    }
}