// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EstimateByCreator
    {
        public string CreatingDirectorate { get; set; }
        public int EngineeringEstimateId { get; set; }
        public bool? IsSingleBidderContract { get; set; }
    }
}