// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EstimateView
    {
        public int EngineeringEstimateId { get; set; }
        public int BoQitemEntryId { get; set; }
        public int? ItemId { get; set; }
        public decimal? Quantity { get; set; }
        public bool? IsSps { get; set; }
        public byte[] RateEncrypted { get; set; }
        public string SeriesDescription { get; set; }
        public decimal? Rate { get; set; }
        public string SeriesSpec { get; set; }
        public string ItemSpec { get; set; }
        public int? PsCode { get; set; }
        public string UnitMeasure { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public bool? Custom { get; set; }
        public decimal? PlacingPerformanceRate { get; set; }
        public int AnalysisType { get; set; }
    }
}