// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class EvsSetting
    {
        public int SettingId { get; set; }
        public decimal? TerrainFactorFlat { get; set; }
        public decimal? TerrainFactorHilly { get; set; }
        public decimal? TerrainFactorEscrapment { get; set; }
        public decimal? TerrainFactorMountainous { get; set; }
        public decimal? LabourIndex { get; set; }
        public decimal? LabourIIndex { get; set; }
        public decimal? LabourIndexArid { get; set; }
        public decimal? BasicSalaryAridFactor { get; set; }
        public decimal? SiteOverhead { get; set; }
        public decimal? HqOverhead { get; set; }
        public decimal? Profit { get; set; }
        public decimal? Risk { get; set; }
        public decimal? WorkingDays { get; set; }
        public decimal? TruckLoadUnloadTime { get; set; }
        public decimal? HaulAggregateToBitumenPlant { get; set; }
        public decimal? HaulAggregateToConcretePrecastSite { get; set; }
        public decimal? HaulAggregateToPlacing { get; set; }
        public decimal? HaulBitumenToPlacing { get; set; }
        public decimal? HaulConcreteToBridges { get; set; }
        public decimal? HaulEarthworkToPlacingOrSpoil { get; set; }
        public decimal? HaulPrecastConcreteMaterialToPlacing { get; set; }
        public decimal? HaulCementToSite { get; set; }
        public decimal? HaulSandToSite { get; set; }
        public decimal? HaulSiteWonSandToPlacing { get; set; }
        public decimal? HaulSelectedEarthworksToPlacing { get; set; }
        public decimal? HaulGravelToPlacing { get; set; }
        public decimal? StandardSpeed { get; set; }
        public decimal? WorkingHoursPerDay { get; set; }
        public decimal? FuelPrice { get; set; }
        public decimal? MinimumKm { get; set; }
        public decimal? MaximumKm { get; set; }
        public decimal? MinimumKph { get; set; }
        public decimal? MaximumKph { get; set; }
        public decimal? DistanceFromAa { get; set; }
        public decimal? FuelPriceAddisAbaba { get; set; }
        public decimal? FuelPriceAfar { get; set; }
        public decimal? FuelPriceAmhara { get; set; }
        public decimal? FuelPriceBenishangulGumuz { get; set; }
        public decimal? FuelPriceDireDawa { get; set; }
        public decimal? FuelPriceGambela { get; set; }
        public decimal? FuelPriceHarari { get; set; }
        public decimal? FuelPriceOromia { get; set; }
        public decimal? FuelPriceSomali { get; set; }
        public decimal? FuelPriceSnnp { get; set; }
        public decimal? FuelPriceTigray { get; set; }
        public int? ObservationInclusionCutoffPercentage { get; set; }
        public int? ItemRateRedFlaggingCutoffFactor { get; set; }
        public decimal? Above4000Turbo { get; set; }
        public decimal? Above3500Turbo { get; set; }
        public decimal? Above3000Turbo { get; set; }
        public decimal? Above2000Turbo { get; set; }
        public decimal? Below2000Turbo { get; set; }
        public decimal? Above3000 { get; set; }
        public decimal? Above2400 { get; set; }
        public decimal? Above1800 { get; set; }
        public decimal? Above1200 { get; set; }
        public decimal? Above600 { get; set; }
        public decimal? Below600 { get; set; }
        public int? HistoricRateLookBackPeriod { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public decimal? LabourIndexMms { get; set; }
        public decimal? WorkingDaysMms { get; set; }
    }
}