// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FileStorageMetadatum
    {
        public FileStorageMetadatum()
        {
            FileStorages = new HashSet<FileStorage>();
        }

        public int DocId { get; set; }
        public int OwnerId { get; set; }
        public string OwnerType { get; set; }
        public string ContentType { get; set; }
        public int FileSize { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }

        public virtual ICollection<FileStorage> FileStorages { get; set; }
    }
}