// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FileStorage
    {
        public int FileId { get; set; }
        public int DocId { get; set; }
        public Guid DocumentFileId { get; set; }
        public byte[] DocumentFile { get; set; }

        public virtual FileStorageMetadatum Doc { get; set; }
    }
}