// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FileUpload
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public int OwnershipId { get; set; }

        public virtual Ownership Ownership { get; set; }
    }
}