// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FinancialInstitute
    {
        public FinancialInstitute()
        {
            Guarantees = new HashSet<Guarantee>();
        }

        public int FinancialInstituteId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Guarantee> Guarantees { get; set; }
    }
}