// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FinancedBy
    {
        public int FinancedById { get; set; }
        public string FinancedByname { get; set; }
        public int NoofDateExpected { get; set; }
    }
}