// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Firm
    {
        public Firm()
        {
            Bidders = new HashSet<Bidder>();
            Contracts = new HashSet<Contract>();
            JvDetails = new HashSet<JvDetail>();
        }

        public int FirmId { get; set; }
        public string FirmType { get; set; }
        public string FirmName { get; set; }
        public string CountryofOrigin { get; set; }
        public int? YearEstablished { get; set; }
        public string ConstructionLicenseNo { get; set; }
        public decimal? RegisteredCapital { get; set; }
        public string Tin { get; set; }
        public string Vatno { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Subcity { get; set; }
        public string Wereda { get; set; }
        public string Pobox { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public bool? IsJointVenture { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastEditedBy { get; set; }

        public virtual ICollection<Bidder> Bidders { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<JvDetail> JvDetails { get; set; }
    }
}