// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FundSourceLookup
    {
        public FundSourceLookup()
        {
            FundSources = new HashSet<FundSource>();
            ProjectFunders = new HashSet<ProjectFunder>();
        }

        public string FundSource { get; set; }

        public virtual ICollection<FundSource> FundSources { get; set; }
        public virtual ICollection<ProjectFunder> ProjectFunders { get; set; }
    }
}