// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class FundSource
    {
        public int FundSourceId { get; set; }
        public int? EngineeringEstimateId { get; set; }
        public string FundSource1 { get; set; }
        public string FundType { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string LastEditedBy { get; set; }
        public string CreatedBy { get; set; }

        public virtual EngineeringEstimate EngineeringEstimate { get; set; }
        public virtual FundSourceLookup FundSource1Navigation { get; set; }
    }
}