// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class GuaranteeType
    {
        public GuaranteeType()
        {
            Guarantees = new HashSet<Guarantee>();
        }

        public string Type { get; set; }
        public string Category { get; set; }
        public string LastEditedBy { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }

        public virtual ICollection<Guarantee> Guarantees { get; set; }
    }
}