// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Guarantee
    {
        public Guarantee()
        {
            GuaranteeCurrencyBreakdowns = new HashSet<GuaranteeCurrencyBreakdown>();
            InverseParentNavigation = new HashSet<Guarantee>();
        }

        public int GuaranteeId { get; set; }
        public int ContractId { get; set; }
        public int FinancialInstituteId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string GuaranteeType { get; set; }
        public decimal? GuaranteeAmountEtb { get; set; }
        public bool? IsExpired { get; set; }
        public int? Parent { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public bool? IsRenewed { get; set; }
        public bool? StopMonitoring { get; set; }
        public string Remark { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual FinancialInstitute FinancialInstitute { get; set; }
        public virtual GuaranteeType GuaranteeTypeNavigation { get; set; }
        public virtual Guarantee ParentNavigation { get; set; }
        public virtual ICollection<GuaranteeCurrencyBreakdown> GuaranteeCurrencyBreakdowns { get; set; }
        public virtual ICollection<Guarantee> InverseParentNavigation { get; set; }
    }
}