// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Head
    {
        public int HeadId { get; set; }
        public int? PhaseId { get; set; }
        public string Head1 { get; set; }

        public virtual Phase Phase { get; set; }
    }
}