// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class HistoricRate
    {
        public int ItemId { get; set; }
        public DateTime? TenderIssueDate { get; set; }
        public decimal? ContractorRate { get; set; }
        public int TenderId { get; set; }
        public bool? ItemRateIncludesVat { get; set; }
        public decimal? Vat { get; set; }
        public int TypeId { get; set; }
        public int BidItemId { get; set; }
        public string ContractType { get; set; }
        public string ControllingRegion { get; set; }
        public int EngineeringEstimateId { get; set; }
    }
}