// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Ipc
    {
        public int Ipcid { get; set; }
        public int? ContractId { get; set; }
        public DateTime? FirstIpcdate { get; set; }
        public DateTime? LastIpcdate { get; set; }

        public virtual Contract Contract { get; set; }
    }
}