// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Issue
    {
        public Issue()
        {
            Appraisals = new HashSet<Appraisal>();
            DisputedIssues = new HashSet<DisputedIssue>();
        }

        public int IssueId { get; set; }
        public int? HeadId { get; set; }
        public string Reference { get; set; }
        public string Issue1 { get; set; }
        public string Indicator { get; set; }
        public string Keywords { get; set; }
        public bool? Era1 { get; set; }
        public bool? Era2 { get; set; }
        public bool? Designer { get; set; }
        public bool? Supervisor { get; set; }
        public bool? Contractor { get; set; }
        public bool? MaintenanceSupervisor { get; set; }
        public bool? MaintenanceContractor { get; set; }
        public bool? DesignBuildDesign { get; set; }
        public bool? DesignBuildBuild { get; set; }
        public bool? DesignBuildEmployerRep { get; set; }
        public bool? Monitor { get; set; }
        public bool? Evaluation { get; set; }
        public bool IsFailable { get; set; }
        public string AppliesTo { get; set; }
        public string AppraisableType { get; set; }

        public virtual ResponseGuideline ResponseGuideline { get; set; }
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        public virtual ICollection<DisputedIssue> DisputedIssues { get; set; }
    }
}