// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ItemWorkMethod
    {
        public int MethodId { get; set; }
        public int? ItemId { get; set; }
        public string WorkMethod { get; set; }

        public virtual Item Item { get; set; }
    }
}