// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class JcoBackup
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public string Directorate { get; set; }
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public DateTime? HiredDate { get; set; }
        public string Category { get; set; }
        public string Skill { get; set; }
        public string DisablityType { get; set; }
        public int MonthlySalary { get; set; }
        public string RegisteredBy { get; set; }
        public string HiredBy { get; set; }
        public int ServiceMonth { get; set; }
        public int ComulativeSalary { get; set; }
        public string Status { get; set; }
        public DateTime LastPaidDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}