// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class KeyStaffRegisterFile
    {
        public int StaffFileId { get; set; }
        public int? StaffId { get; set; }
        public string StaffFileName { get; set; }
    }
}