// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class LabourCostLocal
    {
        public int LabourCostId { get; set; }
        public int? MaterialId { get; set; }
        public int? HauledMaterialId { get; set; }
        public int? Trade { get; set; }
        public int? OperatedEquipmentCostId { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Cost { get; set; }
        public string Activity { get; set; }
        public string Note { get; set; }

        public virtual Material Material { get; set; }
        public virtual EquipmentCostLocal OperatedEquipmentCost { get; set; }
        public virtual Labour TradeNavigation { get; set; }
    }
}