// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class MaterialCost
    {
        public MaterialCost()
        {
            EquipmentCosts = new HashSet<EquipmentCost>();
        }

        public int MaterialCostId { get; set; }
        public int? ItemId { get; set; }
        public int? MaterialId { get; set; }
        public decimal? BulgeFactor { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Cost { get; set; }
        public string Activity { get; set; }
        public string Note { get; set; }

        public virtual Item Item { get; set; }
        public virtual Material Material { get; set; }
        public virtual ICollection<EquipmentCost> EquipmentCosts { get; set; }
    }
}