// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Material
    {
        public Material()
        {
            EquipmentCostLocals = new HashSet<EquipmentCostLocal>();
            LabourCostLocals = new HashSet<LabourCostLocal>();
            MaterialCostLocals = new HashSet<MaterialCostLocal>();
            MaterialCosts = new HashSet<MaterialCost>();
        }

        public int MaterialId { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialUnit { get; set; }
        public decimal? PurchasePrice { get; set; }
        public decimal? LoadingUnloading { get; set; }
        public decimal? TruckTravelDistance { get; set; }
        public decimal? TruckTravelHour { get; set; }
        public decimal? TruckRent { get; set; }
        public decimal? TruckCapacity { get; set; }
        public decimal? QuantityPerTruck { get; set; }
        public string HaulSource { get; set; }
        public decimal? ProductionRate { get; set; }
        public decimal? Rate { get; set; }
        public bool? ProducedAtSite { get; set; }
        public string Group { get; set; }
        public bool? IsAggregate { get; set; }
        public bool? IsDirectToPlacing { get; set; }
        public string Note { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public bool IsMaintenanceMaterial { get; set; }

        public virtual ICollection<EquipmentCostLocal> EquipmentCostLocals { get; set; }
        public virtual ICollection<LabourCostLocal> LabourCostLocals { get; set; }
        public virtual ICollection<MaterialCostLocal> MaterialCostLocals { get; set; }
        public virtual ICollection<MaterialCost> MaterialCosts { get; set; }
    }
}