// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class MaterialCostLocal
    {
        public MaterialCostLocal()
        {
            EquipmentCostLocals = new HashSet<EquipmentCostLocal>();
        }

        public int MaterialCostId { get; set; }
        public int? MainMaterialFkid { get; set; }
        public int? ChildMaterialId { get; set; }
        public decimal? BulgeFactor { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Cost { get; set; }
        public string Activity { get; set; }
        public string Note { get; set; }

        public virtual Material ChildMaterial { get; set; }
        public virtual ICollection<EquipmentCostLocal> EquipmentCostLocals { get; set; }
    }
}