// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Measurement
    {
        public Measurement()
        {
            ContractProgressPerformanceScores = new HashSet<ContractProgressPerformanceScore>();
        }

        public int? ContractId { get; set; }
        public int MeasurementId { get; set; }
        public DateTime? Date { get; set; }
        public decimal? MeasurementAndVos { get; set; }
        public decimal? CertifiedClaims { get; set; }
        public decimal? Escalation { get; set; }
        public decimal? TotalRetention { get; set; }
        public decimal? Taxes { get; set; }
        public decimal? InterestOnLatePayments { get; set; }
        public decimal? OtherPayments { get; set; }
        public decimal? AdvanceRepayment { get; set; }
        public decimal? CorrectionOnCertificate { get; set; }
        public decimal? VatThisInvoice { get; set; }
        public decimal? ExpenditureVsBudget { get; set; }
        public string CriticalActivities { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ICollection<ContractProgressPerformanceScore> ContractProgressPerformanceScores { get; set; }
    }
}