// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class MovLookup
    {
        public int MoVid { get; set; }
        public int? LookupId { get; set; }
        public string MoV { get; set; }
    }
}