// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Ownership
    {
        public Ownership()
        {
            FileUploads = new HashSet<FileUpload>();
            Properties = new HashSet<Property>();
        }

        public int OwnershipId { get; set; }
        public string OwnershipName { get; set; }
        public int ProjectPerKmId { get; set; }

        public virtual ProjectPerKm ProjectPerKm { get; set; }
        public virtual ICollection<FileUpload> FileUploads { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}