// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class PasDivisonsWeight
    {
        public int PasWeightId { get; set; }
        public int? PhaseId { get; set; }
        public decimal? Era { get; set; }
        public decimal? Design { get; set; }
        public decimal? Supervision { get; set; }
        public decimal? Works { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }

        public virtual Phase Phase { get; set; }
    }
}