// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class PasFeedback
    {
        public int FeedBackId { get; set; }
        public string Comment { get; set; }
        public DateTime? CommentDate { get; set; }
        public string CommentBy { get; set; }
    }
}