// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Payment
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public DateTime DateRecived { get; set; }
        public string PayeTo { get; set; }
        public string FinancedBy { get; set; }
        public string Region { get; set; }
        public string Ipcinv { get; set; }
        public string Type { get; set; }
        public DateTime DateToprocess { get; set; }
        public DateTime PayDate { get; set; }
        public string Status { get; set; }
        public string CounterAccount { get; set; }
        public string Team { get; set; }
        public string TeamLeader { get; set; }
        public DateTime? DateReturn { get; set; }
        public string Paidstatus { get; set; }
        public string ProjectName { get; set; }
        public string Remark { get; set; }
        public string LastEditedBy { get; set; }

        public virtual Project Project { get; set; }
    }
}