// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class PhaseCurrencyBreakdown
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int ContractPhaseId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Currency { get; set; }
        public decimal ExchangeRate { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public string Type { get; set; }

        public virtual ContractPhase ContractPhase { get; set; }
    }
}