// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Phase
    {
        public Phase()
        {
            Heads = new HashSet<Head>();
            PasDivisonsWeights = new HashSet<PasDivisonsWeight>();
        }

        public int PhaseId { get; set; }
        public string Phase1 { get; set; }

        public virtual ICollection<Head> Heads { get; set; }
        public virtual ICollection<PasDivisonsWeight> PasDivisonsWeights { get; set; }
    }
}