// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ProjectPerKm
    {
        public ProjectPerKm()
        {
            EstimateCommittes = new HashSet<EstimateCommitte>();
            Ownerships = new HashSet<Ownership>();
        }

        public int ProjectPerKmId { get; set; }
        public decimal Kmstart { get; set; }
        public decimal KmEnd { get; set; }
        public int ProjectId { get; set; }
        public string State { get; set; }
        public string Woreda { get; set; }
        public string Zone { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<EstimateCommitte> EstimateCommittes { get; set; }
        public virtual ICollection<Ownership> Ownerships { get; set; }
    }
}