// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ProjectFunder
    {
        public int ProjectFunderId { get; set; }
        public int? ProjectId { get; set; }
        public string FundSource { get; set; }
        public string FundType { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public string LastEditedBy { get; set; }

        public virtual FundSourceLookup FundSourceNavigation { get; set; }
        public virtual Project Project { get; set; }
    }
}