// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string Category { get; set; }
        public DateTime EndDate { get; set; }
        public string EraConsultant { get; set; }
        public string IsPermanent { get; set; }
        public int Latitude { get; set; }
        public int Longtiude { get; set; }
        public string Measurement { get; set; }
        public string OutsideConsultant { get; set; }
        public int OwnershipId { get; set; }
        public string PassionDate { get; set; }
        public DateTime PaymentDate { get; set; }
        public string PropertyType { get; set; }
        public string Quantity { get; set; }
        public decimal SinglePrice { get; set; }
        public DateTime StartDate { get; set; }
        public decimal TotalPrice { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }

        public virtual Ownership Ownership { get; set; }
    }
}