// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class PurchaseItem
    {
        public int ItemNo { get; set; }
        public string Article { get; set; }
        public string ClassCode { get; set; }
        public string ImbNo { get; set; }
        public int? QuantityReceived { get; set; }
        public int? QuantityOrdered { get; set; }
        public string Unit { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? Amount { get; set; }
        public int? PurchaseNo { get; set; }
    }
}