// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class QuantityChangeCategory
    {
        public QuantityChangeCategory()
        {
            QuantityChangeSubCategories = new HashSet<QuantityChangeSubCategory>();
            QuantityChanges = new HashSet<QuantityChange>();
        }

        public string Category { get; set; }

        public virtual ICollection<QuantityChangeSubCategory> QuantityChangeSubCategories { get; set; }
        public virtual ICollection<QuantityChange> QuantityChanges { get; set; }
    }
}