// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Remark
    {
        public int RemarkId { get; set; }
        public string RemarkName { get; set; }
    }
}