// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class ResponseGuideline
    {
        public int IssueId { get; set; }
        public string Good { get; set; }
        public string Acceptable { get; set; }
        public string Poor { get; set; }
        public string Unacceptable { get; set; }
        public string Fail { get; set; }

        public virtual Issue Issue { get; set; }
    }
}