// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class RoadSegmentList
    {
        public int RnmdId { get; set; }
        public string RoadAdmin { get; set; }
        public int? Asphaltlength { get; set; }
        public string DsStandard { get; set; }
        public int? Gravellength { get; set; }
        public string GtpPlan { get; set; }
        public string Region { get; set; }
        public DateTime? RegistraionYear { get; set; }
        public string Rnmd { get; set; }
        public string RoadClass { get; set; }
        public string RoadNo { get; set; }
        public string Roadstatus { get; set; }
        public string Section { get; set; }
        public string SegmentName { get; set; }
        public string SegmentNo { get; set; }
        public int? Totallength { get; set; }
    }
}