// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Rsdp
    {
        public Rsdp()
        {
            Projects = new HashSet<Project>();
        }

        public string Rsdp1 { get; set; }
        public string Description { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }

        public virtual ICollection<Project> Projects { get; set; }
    }
}