// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Series
    {
        public Series()
        {
            BidSeries = new HashSet<BidSeries>();
            BoQseriesEntries = new HashSet<BoQseriesEntry>();
            Divisions = new HashSet<Division>();
        }

        public string SeriesCode { get; set; }
        public string SeriesDescription { get; set; }
        public string SpecificationName { get; set; }

        public virtual ICollection<BidSeries> BidSeries { get; set; }
        public virtual ICollection<BoQseriesEntry> BoQseriesEntries { get; set; }
        public virtual ICollection<Division> Divisions { get; set; }
    }
}