// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Supplement
    {
        public Supplement()
        {
            ContractPhaseReplacedSupplements = new HashSet<ContractPhase>();
            ContractPhaseSupplements = new HashSet<ContractPhase>();
        }

        public int Id { get; set; }
        public DateTime AgreementDate { get; set; }
        public int ContractId { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public string Purpose { get; set; }
        public decimal SupplementAmount { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime LastModifiedOn { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ICollection<ContractPhase> ContractPhaseReplacedSupplements { get; set; }
        public virtual ICollection<ContractPhase> ContractPhaseSupplements { get; set; }
    }
}