// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class TeamLeaderNote
    {
        public int NoteId { get; set; }
        public int? ContractId { get; set; }
        public DateTime? CurrentNoteDate { get; set; }
        public DateTime? LastNoteDate { get; set; }
        public string Note { get; set; }
        public string LastEditedBy { get; set; }

        public virtual Contract Contract { get; set; }
    }
}