// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class Tender
    {
        public Tender()
        {
            Bidders = new HashSet<Bidder>();
            Bids = new HashSet<Bid>();
            CacReleasedTenders = new HashSet<CacReleasedTender>();
        }

        public int TenderId { get; set; }
        public int? EngineeringEstimateId { get; set; }
        public string TenderNumber { get; set; }
        public string TenderName { get; set; }
        public DateTime? TenderIssueDate { get; set; }
        public DateTime? TenderClosingDate { get; set; }
        public DateTime? TenderOpeningDate { get; set; }
        public string TenderType { get; set; }
        public bool? TenderCanceled { get; set; }
        public DateTime? CancelationDate { get; set; }
        public string CacSecretaryNote { get; set; }
        public bool? TenderAwarded { get; set; }
        public string CreatedBy { get; set; }
        public bool? IsReleased { get; set; }
        public bool? IsSubmitted { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModifiedOn { get; set; }

        public virtual EngineeringEstimate EngineeringEstimate { get; set; }
        public virtual TacReleasedTender TacReleasedTender { get; set; }
        public virtual ICollection<Bidder> Bidders { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<CacReleasedTender> CacReleasedTenders { get; set; }
    }
}