// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class TransformedContractValue
    {
        public int EntryId { get; set; }
        public int ContractId { get; set; }
        public decimal? ContractAmountExcludingVat { get; set; }
        public decimal? ContractAmountExcludingContingency { get; set; }
        public decimal? ContractAmountIncludingVatandExcludingContingency { get; set; }
        public DateTime? OriginalCompletionDate { get; set; }
        public DateTime? RevisedCompletionDate { get; set; }
        public string DelayDescription { get; set; }
        public decimal? Delay { get; set; }
        public decimal? MeasureChange { get; set; }
        public decimal? RequestedVariationOrder { get; set; }
        public decimal? RecommendedVariationOrder { get; set; }
        public decimal? ApprovedVariationOrder { get; set; }
        public decimal? RequestedClaim { get; set; }
        public decimal? RecommendedClaim { get; set; }
        public decimal? ApprovedClaim { get; set; }
        public decimal? RequestedPredictedCostExcludingEscalation { get; set; }
        public decimal? RecommendedPredictedCostExcludingEscalation { get; set; }
        public decimal? ApprovedPredictedCostExcludingEscalation { get; set; }
        public decimal? RequestedPredictedCostIncludingVat { get; set; }
        public decimal? RecommendedPredictedCostIncludingVat { get; set; }
        public decimal? ApprovedPredictedCostIncludingVat { get; set; }
        public int? RequestedEot { get; set; }
        public int? RecommendedEot { get; set; }
        public int? ApprovedEot { get; set; }
        public DateTime? RequestedPredictedCompletion { get; set; }
        public DateTime? RecommendedPredictedCompletion { get; set; }
        public DateTime? ApprovedPredictedCompletion { get; set; }
        public DateTime? LastMeasurementDate { get; set; }
        public decimal? LastMeasurement { get; set; }
        public decimal? Escalation { get; set; }
        public decimal? Retention { get; set; }
        public decimal? OutstandingAdvance { get; set; }
        public decimal? GrandTotalExcludingVat { get; set; }
        public decimal? Vat { get; set; }
        public decimal? GrandTotalIncludingVat { get; set; }
        public decimal? RecommendedFinancialPercentageCompleted { get; set; }
        public decimal? ApprovedFinancialPercentageCompleted { get; set; }
        public decimal? PercentageElapsedAtRecommended { get; set; }
        public decimal? PercentageElapsedAtApproved { get; set; }
        public bool? ItemRatesIcludeVat { get; set; }
        public decimal? PredictedIncontractContingency { get; set; }
        public decimal? PredictedUsedContingency { get; set; }
        public decimal? AdditionToContractValue { get; set; }
        public decimal? QuantityChageTotalCost { get; set; }
        public decimal? CumulativeSpentAgainstAnnualBudget { get; set; }
        public decimal? CumulativePercentageSpentAgainstAnnualBudget { get; set; }
        public string CriticalActivity { get; set; }
        public string MeasurementLastEditedBy { get; set; }
        public decimal? ProgressPerformance { get; set; }
        public string ProgressPerformanceMessage { get; set; }
        public string TeamLeaderNote { get; set; }
        public DateTime? TeamLeaderNoteDate { get; set; }
        public string TeamLeaderUserName { get; set; }
        public string LengthBySurfaceType { get; set; }
        public decimal? TotalRoadLength { get; set; }
        public decimal? EquivalentPhysicalWork { get; set; }
        public decimal? OriginalRatePerKm { get; set; }
        public decimal? PredictedRatePerKm { get; set; }
        public decimal? MaxRoadWidth { get; set; }
        public decimal? OriginalRatePerLane { get; set; }
        public decimal? PredictedRatePerLane { get; set; }
        public decimal? OriginalContractAmount { get; set; }
    }
}