// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class UnitMeasure
    {
        public UnitMeasure()
        {
            Items = new HashSet<Item>();
        }

        public string UnitMeasure1 { get; set; }

        public virtual ICollection<Item> Items { get; set; }
    }
}