// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class UtilContract
    {
        public int ContractId { get; set; }
        public int? EngineeringEstimateId { get; set; }
        public int? DesignContractId { get; set; }
        public int? WorkContractId { get; set; }
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public string ContractType { get; set; }
        public string ControllingRegion { get; set; }
        public bool? IsAwarded { get; set; }
        public bool? IsSingleBidderContract { get; set; }
        public int? Contractor { get; set; }
    }
}