// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class VariationOrderCategory
    {
        public VariationOrderCategory()
        {
            VariationOrderSubcategories = new HashSet<VariationOrderSubcategory>();
            VariationOrders = new HashSet<VariationOrder>();
        }

        public string Category { get; set; }

        public virtual ICollection<VariationOrderSubcategory> VariationOrderSubcategories { get; set; }
        public virtual ICollection<VariationOrder> VariationOrders { get; set; }
    }
}