// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class VatInclusiveColumenUpdateForPawe
    {
        public int? ProjectId { get; set; }
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public int? Contractor { get; set; }
        public string ContractType { get; set; }
        public decimal? Vat { get; set; }
        public decimal? VatRate { get; set; }
        public bool? VatInclusive { get; set; }
    }
}