// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class WinningBid
    {
        public int ContractId { get; set; }
        public int EngineeringEstimateId { get; set; }
        public int BidderId { get; set; }
        public bool? IsWinner { get; set; }
        public int TenderId { get; set; }
    }
}