// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class AspnetRole
    {
        public AspnetRole()
        {
            MandatoryRolesMatrices = new HashSet<MandatoryRolesMatrix>();
            Users = new HashSet<AspnetUser>();
        }

        public Guid ApplicationId { get; set; }
        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string LoweredRoleName { get; set; }
        public string Description { get; set; }

        public virtual AspnetApplication Application { get; set; }
        public virtual ICollection<MandatoryRolesMatrix> MandatoryRolesMatrices { get; set; }

        public virtual ICollection<AspnetUser> Users { get; set; }
    }
}