// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERAManagementSystem.Models
{
    public partial class MandatoryRolesMatrix
    {
        public int MandatoryRoleId { get; set; }
        public string Directorate { get; set; }
        public string Position { get; set; }
        public Guid? MandatoryRole { get; set; }

        public virtual AspnetRole MandatoryRoleNavigation { get; set; }
    }
}